### ISSUE TITLE
Create Register page HTML template

### ISSUE THREAD

**Issue by Rwothoromo** [Rwothoromo/dreams#10]
**Is your feature request related to a problem? Please describe.**
Currently, there is no HTML template for the Register page.

**Describe the solution you'd like**
Create a template based on the [wireframe](./wireframes/register.PNG).

**Describe alternatives you've considered**
Any HTML template close to the wireframe design will do.

**Additional context**
This is the proposed design.
![image](https://user-images.githubusercontent.com/7848682/46348878-187c7a00-c659-11e8-91c0-aba5f7952b0a.png)

**Comment by pranikamassey** [comment]
Can I work on this?

**Comment by Rwothoromo** [comment]
Sure do @pranikamassey.
