### ISSUE TITLE
Make a Flask app

### ISSUE THREAD

**Issue by Rwothoromo** [Rwothoromo/dreams#11]
**Is your feature request related to a problem? Please describe.**
Functionality should be added for this application.

**Describe the solution you'd like**
Make this application a Flask app.

**Describe alternatives you've considered**
This could easily be a Django application but we will go with Flask

**Additional context**
For a quick start, take a look at [Flask website](http://flask.pocoo.org/) or [Flask tutorial](https://scotch.io/tutorials/getting-started-with-flask-a-python-microframework)

**Comment by sudoalgorithm** [comment]
I want to work on this.

**Comment by Rwothoromo** [comment]
@sudoalgorithm, sure do

**Comment by Rwothoromo** [comment]
@sudoalgorithm I have updated a number of things, could you rebase and make `python app.py` work?

**Comment by sudoalgorithm** [comment]
@Rwothoromo you need to add the mongodb configuration(DB name, host address and port) in the config.py file to make the app work. add them it will work.

**Comment by Rwothoromo** [comment]
@sudoalgorithm Could you add those details say, `db setup` on the `README`?

**Comment by sudoalgorithm** [comment]
Sure, give me time till 2moro
