### ISSUE TITLE
Create a User model

### ISSUE THREAD

**Issue by Rwothoromo** [Rwothoromo/dreams#18]
**Is your feature request related to a problem? Please describe.**
Currently, there is no User model.

**Describe the solution you'd like**
Create a `./src/models/user.py` class and populate it with the user model based on the [design](https://github.com/Rwothoromo/dreams/blob/master/src/designs/UML/UML%20Class%20Diagrams.png).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by asi7296** [comment]
I'd like to work on this.

**Comment by Rwothoromo** [comment]
@asi7296 Please do 😎

**Comment by asi7296** [comment]
@Rwothoromo Is there a description of the function parameters and the expected returns? As in the logic behind the functions? Or should I just make a skeleton class now which will be implemented later?

**Comment by Rwothoromo** [comment]
@asi7296 A skeleton will do for now. I will add stories for API endpoints.
For now, just add the model with the `__init__` function.
