### ISSUE TITLE
Create a bucket list model

### ISSUE THREAD

**Issue by Rwothoromo** [Rwothoromo/dreams#19]
Is your feature request related to a problem? Please describe.
Currently, there is no bucket list model.

Describe the solution you'd like
Create a `./src/models/bucketlist.py` class and populate it with the bucket list model based on the [design](https://github.com/Rwothoromo/dreams/blob/master/src/designs/UML/UML%20Class%20Diagrams.png).

Describe alternatives you've considered
N/A

Additional context
N/A

**Comment by asi7296** [comment]
I'll do this one too. Should I make the filenames lowercase? I'll change User too in that case.

**Comment by Rwothoromo** [comment]
Yes, sure do.

**Comment by asi7296** [comment]
PR #21
