### ISSUE TITLE
Format the Readme better

### ISSUE THREAD

**Issue by Rwothoromo** [Rwothoromo/dreams#22]
**Is your feature request related to a problem? Please describe.**
The `Readme` is not well formatted.

**Describe the solution you'd like**
Structure it better; [for example](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Vinetos** [comment]
I'm on it

**Comment by evenzdev** [comment]
working on it :)

**Comment by bhaskarmac** [comment]
I can work on this
