### ISSUE TITLE
Make Readme more descriptive

### ISSUE THREAD

**Issue by Rwothoromo** [Rwothoromo/dreams#3]
This Repository is for a Bucketlist application. Make the README more descriptive ([for example](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2)).
1. Fork this Repository.
2. Add how to set up the Repository on a local machine.
3. Also, add details of how a contributor should add their details to `Contributors.md` in the format available.
4. Raise a PR from your `fork` to this Repo.

Happy Hacktoberfest 2018!

**Comment by flexbox** [comment]
Looks there is no `develop` branch 😉

**Comment by Rwothoromo** [comment]
Thank you @flexbox , I have updated the issue 🤓.
