### ISSUE TITLE
Create bucket lists HTML template.

### ISSUE THREAD

**Issue by Rwothoromo** [Rwothoromo/dreams#8]
**Is your feature request related to a problem? Please describe.**
Currently, there is no HTML template for the bucket lists.

**Describe the solution you'd like**
Create a template based on the [wireframe](./wireframes/bucketlists.PNG).

**Describe alternatives you've considered**
Any HTML template close to the wireframe design will do.

**Additional context**
This is the proposed design.
![image](https://user-images.githubusercontent.com/7848682/46348583-1e259000-c658-11e8-8345-3c9e2b59e823.png)

**Comment by yurichandra** [comment]
May i work on this?

**Comment by Rwothoromo** [comment]
Sure do @yurichandra
