### ISSUE TITLE
Create a Login HTML template

### ISSUE THREAD

**Issue by Rwothoromo** [Rwothoromo/dreams#9]
**Is your feature request related to a problem? Please describe.**
Currently, there is no HTML template for the Login page.

**Describe the solution you'd like**
Create a template based on the [wireframe](./wireframes/login.PNG).

**Describe alternatives you've considered**
Any HTML template close to the wireframe design will do.

**Additional context**
This is the proposed design.
![image](https://user-images.githubusercontent.com/7848682/46348814-e0753700-c658-11e8-9cd9-459e85d7d323.png)

**Comment by pranikamassey** [comment]
Can I work on this?
